### ISSUE TITLE
Missing JSON property "OperatorID" in eRoamingChargingNotifications Error documentation

### ISSUE THREAD

**Issue by ahzf** [hubject/oicp#100]
The example of the eRoamingChargingNotificationError at https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20CPO/06_CPO_Code_Snippets.asciidoc#15-eroamingchargingnotificationerror has an **OperatorID** property, but the documentation at In https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20CPO/02_CPO_Services_and_Operations.asciidoc#64-eroamingchargingnotifications-error is missing this information. This will result in the following not very helpful HTTP error message:

```
HTTP/1.1 500
Server:          nginx/1.18.0 (Ubuntu)
Date:            Sat, 06 Aug 2022 06:33:53 GMT
Content-Type:    application/json;charset=ISO-8859-1
Content-Length:  108
Connection:      close
Process-ID:      90163b8e-3301-4538-a7d9-82d7734879b4

{
  "StatusCode": {
    "Code":            "001",
    "Description":     "Unexpected error checking partners: null",
    "AdditionalInfo":   null
  }
}
```

Also in all other charging notifications the **OperatorID** is optional, but here it seems to be mandatory. Was this intended?

**Comment by moghaffari** [comment]
@ahzf  Please provider the full request body and url you're calling.
