### ISSUE TITLE
Missing Picture in 02_EMP_Services_and_Operations

### ISSUE THREAD

**Issue by cluettig** [hubject/oicp#22]
Within the Page [02_EMP_Services_and_Operations](https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20EMP/02_EMP_Services_and_Operations.asciidoc#31-eroamingpushauthenticationdata_v21)

Pushauthethication picture is missing

**Comment by oicp-moderator** [comment]
Hi Cluettig, 

Thank you for your feedback. We have made the proper adaptations for the image to be displayed. 

Best regards, 
Your Hubject Team

**Comment by oicp-moderator** [comment]
Hi Cluettig,

Thank you for your feedback. We have made the proper adaptations for the image to be displayed.

Best regards,
Your Hubject Team
