### ISSUE TITLE
Uncertanties within EvseDatapull

### ISSUE THREAD

**Issue by cluettig** [hubject/oicp#23]
Within the Page [02_EMP_Services_and_Operations](https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20EMP/02_EMP_Services_and_Operations.asciidoc#41-eroamingpullevsedata_v23), it would be beneficial to get an example for the Deltapull URL's how they should be used.

It would be also beneficial for the size of the Pages if there is a upper limit

**Comment by oicp-moderator** [comment]
Hi Cluettig, 

thank you for your feedback. 

We have made some adaptations to the docuemntation. 

Best regards, 
Your Hubject Team
