### ISSUE TITLE
Consistency problems between docs and samples [eRoamingPullEVSEData ]

### ISSUE THREAD

**Issue by lgualtieri75** [hubject/oicp#25]
Hi,
I've found this problems with the provided response.json sample.

"Address": "TimeZone": "UTC+01:00" in docs, "Address": "TimeZone": "string",
"OpeningTimesType": "Periods" in docs, "OpeningTimesType": "Period" in the example
"OpeningTimesType": "On" in docs, "OpeningTimesType":"on" in the example

**Comment by oicp-moderator** [comment]
HI Igualtieri75, 

Thank you for your valuable feedback, we have made the proper adjustments to the documentation. 

Have an excellent day. 

Best regards, 
Your Hubject Team.
