### ISSUE TITLE
Definition of Transparancy Software

### ISSUE THREAD

**Issue by cluettig** [hubject/oicp#29]
Within the Documentation [1.34 SignedMeteringValuesType](https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20EMP/03_EMP_Data_Types.asciidoc#134-signedmeteringvaluestype) `the Transparency Software` is mentioned

Pls define to which Transparency Software this referes

**Comment by oicp-moderator** [comment]
Hi Cluettig, 

We have added specified in the description which Transparency software must be referred. Please have in mind that each CPO can use a different transparency softwares. 

Best regards, 
Your Hubject Team
