### ISSUE TITLE
eRoamingChargingNotifications interface is not present in swagger documentation

### ISSUE THREAD

**Issue by lgualtieri75** [hubject/oicp#37]

**Comment by oicp-moderator** [comment]
Hi Igualtieri75, 

Thank you for contacting us, we are reviewing this topic. As soon we have news regarding this topic we will come back to you. 

Best regards, 
Your Hubject Team

**Comment by moghaffari** [comment]
The OpenAPI documentation has been added via https://github.com/hubject/oicp/pull/108
