### ISSUE TITLE
Authentication documentation has wrong request/response types

### ISSUE THREAD

**Issue by tomkuijsten** [hubject/oicp#42]
The Request and Response types seems to be wrong at "3.1. eRoamingPushAuthenticationData_V2.1".

Request message: eRoamingAuthorizeRemoteReservationStop
Response message: eRoamingAcknowledgement

https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20EMP/02_EMP_Services_and_Operations.asciidoc#3-eroamingauthenticationdata

**Comment by oicp-moderator** [comment]
Hi Tom, 

Thank you for your feedback, we have made the proper change to the documentation. 

Best regards, 
Your Hubject Team
