### ISSUE TITLE
Broken link to OICP v2.3 Realease Notes

### ISSUE THREAD

**Issue by ahzf** [hubject/oicp#44]
In https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20CPO/00_README_CPO.md the link https://github.com/oicp-moderator/OICP-2.3-Draft/blob/master/Realease_Notes.asciidoc is not valid. I guess the correct link is: https://github.com/hubject/oicp/blob/master/OICP-2.3/Realease_Notes.asciidoc

**Comment by oicp-moderator** [comment]
Hi ahzf, 

Thank you for your feedback, 

We have made the proper change of the link to the Release Notes documentation. 

Best regards, 
Your Hubject Team
