### ISSUE TITLE
Property "unstructuredOpeningTime" in EVSEDataRecord 

### ISSUE THREAD

**Issue by ahzf** [hubject/oicp#45]
The EVSEDataRecord seems to have a property "unstructuredOpeningTime" in the Swagger definition https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20CPO/03_CPO_Data_Types.asciidoc#OpeningTimesType
 , but this in not defined in the normal documentation https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20CPO/03_CPO_Data_Types.asciidoc#OpeningTimesType

```
{
    "Period": [
        {
            "begin": "string",
            "end":   "string"
        }
    ],
    "on":                      "enum",
    "unstructuredOpeningTime": "string"
}
```

**Comment by oicp-moderator** [comment]
Hi ahzf, 

Thank you for your feedback, we have made the proper changes. It is not present anymore in the Swagger 2.3 documentation. 

Best regards, 
Your Hubject Team
