### ISSUE TITLE
Evse(Data|Status)Record in OperatorEvseStatusType vs OperatorEvseDataType

### ISSUE THREAD

**Issue by ahzf** [hubject/oicp#46]
The Evse(Data|Status)Record is mandatory within OperatorEvseDataType ( https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20CPO/03_CPO_Data_Types.asciidoc#OperatorEvseDataType ) and OperatorEvseStatusType ( https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20CPO/03_CPO_Data_Types.asciidoc#118-operatorevsestatustype ), but the size of those array can be zero.

That is not really usefull for anyone. Both should require an array of at least one Evse(Data|Status)Record.

.

**Comment by oicp-moderator** [comment]
Good morning ahzf, 

Thank you for your comment. 

The field is mandatory but in the documentation it says that 0 entries can be performed and this is to offer a possibility to the CPO to clean up their EVSEData/Status in the HBS with a FullLoad. 

Best regards, 
Your Hubject Team
