### ISSUE TITLE
GeoCoordinates within EVSEDataRecord mandatory or optional?

### ISSUE THREAD

**Issue by ahzf** [hubject/oicp#49]
GeoCoordinates within EVSEDataRecord seems to be optional within the documentation https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20CPO/03_CPO_Data_Types.asciidoc#EvseDataRecordType 

```
GeoCoordinates | GeoCoordinatesType | Geolocation of the charging station. | O | 100
```

but mandatory within the swagger file https://github.com/hubject/oicp/blob/master/OICP-2.3/SWAGGER%20DOCUMENTATION/evse-api-docs-2.3.json 

```
"EvseDataRecord": {
      "type": "object",
      "required": [
        "Accessibility",
        "Address",
        "AuthenticationModes",
        "ChargingStationNames",
        "DynamicInfoAvailable",
        "EvseID",
        "GeoCoordinates",
        "IsHubjectCompatible",
        "IsOpen24Hours",
        "OperatorID",
        "RenewableEnergy"
      ],
```

...and within your implementation:

```
HTTP/1.1 400 
Server: nginx/1.18.0
Date: Fri, 08 Jan 2021 14:19:25 GMT
Content-Type: application/json;charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Process-ID: b87fd67b-2d74-4318-86cf-0d2c2c50cabb

{
	"message": "Error parsing/validating JSON.",
	"validationErrors": [
		{
			"fieldReference": "operatorEvseData.evseDataRecord[0].geoCoordinates",
			"errorMessage": "may not be null"
		}
	]
}
```

Also it is a bit confusing, that all propery keys start with an upper case character within the normal protocol, but when you send this error message the first character is always lower case, e.g. "GeoCoordinates" vs. "operatorEvseData.evseDataRecord[0].geoCoordinates".

**Comment by oicp-moderator** [comment]
Hi ahzf, 

Thank you for your input, we have already made the proper change in the documentation, the GeoCoordinates in this matter are mandatory. 

Best regards, 
Your Hubject Team
