### ISSUE TITLE
Charging notifications are missing within the Swagger specifications

### ISSUE THREAD

**Issue by ahzf** [hubject/oicp#57]
There is the textual documentation of charging notifications https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20CPO/02_CPO_Services_and_Operations.asciidoc#eRoamingChargingNotifications but I can not find anything about Charging notifications within the swagger specifications https://github.com/hubject/oicp/tree/master/OICP-2.3/SWAGGER%20DOCUMENTATION

**Comment by moghaffari** [comment]
The OpenAPI documentation has been added via #108
