### ISSUE TITLE
Feature request: OpenAPI specification of REST API

### ISSUE THREAD

**Issue by bkonetzny** [hubject/oicp#6]
It would be cool to have an [OpenAPI specification](http://spec.openapis.org/oas/v3.0.3) (aka Swagger) of the REST version of OICP for the different versions (or only 2.2) so clients for different programming languages can be generated based on this official specification, rather than implementing everything from scratch.

**Comment by logemann** [comment]
+1

**Comment by moghaffari** [comment]
@bkonetzny and @logemann  The swagger JSON files have been added. Please check the latest commit.
I'll close this and we can revisit it if the provided swagger files are not sufficient.
