### ISSUE TITLE
Is XML still supported in OICP 2.3 ?

### ISSUE THREAD

**Issue by ltkum** [hubject/oicp#91]
Good afternoon,

We're currently updating our OICP stack, and we are still currently supporting SOAP xml payloads (we have operators using them over OICP 2.2). In your documentation (https://github.com/hubject/oicp/blob/master/OICP-2.3/OICP%202.3%20EMP/01_EMP_Communication_Paradigms.asciidoc#rest) you state that all queries should be done using REST. 
Since we're trying to follow the specifications as closely as we can, the question is simple: does the hubject REST API support XML payloads, or is this an old format that you no longer use.

Hope I've not bothered you too much, and I wish you an excellent day.

**Comment by cype** [comment]
up

**Comment by cype** [comment]
@oicp-moderator 
@moghaffari
@mhassan-hubject
@stefflang78

**Comment by ahzf** [comment]
XML via REST is not the same as SOAP/XML, esp. meta data and error handling is very different. Therefore I would assume, that the answer is "no".

**Comment by moghaffari** [comment]
@cype @ltkum The XML format is not supported in the `OICP 2.3`. 
You can still use the `OICP 2.2` with Hubject but the recommendation is to use the latest version of the protocol which is `OICP 2.3`
